# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Log4perl-CommandLine
version:      0.05
version_from: lib/Log/Log4perl/CommandLine.pm
installdirs:  site
requires:
    Getopt::Long:                  0
    Log::Log4perl:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
